spring:
  application:
    name: kc_forum
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kc_forum? characterEncoding=utf8&useSSL=false
    username: root
    password: Zz161011.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss #格式化日期
    default-property-inclusion: non_null #为null的时候不格式化
  mail:
    host: smtp.qq.com
    port: 465
    username: 1624475081@qq.com
    password: gyfiybzapiamjfdf
    protocol: smtp
    properties: # 下面要用properties的写法才可以生效
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true  # 启用SSL
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    #      mail.debug: true  # 开启调试日志
    default-encoding: utf-8
  data:
    redis:
      port: 6379
      host: 127.0.0.1
server:
  port: 58080
#mybatis-plus:
#  configuration: # 配置打印 MyBatis⽇志
#    map-underscore-to-camel-case: true #格式转化
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    root: info #日志默认级别
#    com.doublez.kc_forum: debug #指定包下的日志级别
  file:
    path: /var/log/kc_forum #日志保存路径

upload:
  avatar-base-path: /var/kc_forum/upload # 头像存储的基础路径
  avatar-base-url:  http://119.91.218.96/avatars # 头像访问的基础URL
  base-path: /var/kc_forum/upload
  base-url: http://localhost:58080
jwt:
  secret: FzG6p48J80L6vFxLrQqy2JVN27NiYbgjtGuYCTpeX7w= # 你的密钥，确保足够复杂和保密
  access-token:
    expiration-ms: 1800000 # Access Token 过期时间 (30分钟 = 30 * 60 * 1000)
  refresh-token:
    expiration-ms: 604800000 # Refresh Token 过期时间 (7天 = 7 * 24 * 60 * 60 * 1000)
  proactive-refresh:
    # 提前刷新阈值 (毫秒)，例如 5 分钟: 5 * 60 * 1000 = 300000
    # 如果 Access Token 剩余有效期小于等于此值，则尝试主动刷新
    # 设置为 0 或负数则禁用此功能
    threshold-ms: 300000