import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';

// Load users from JSON file
const users = new SharedArray('users', function () {
    try {
        return JSON.parse(open('./users.json'));
    } catch (e) {
        console.error('Failed to load users.json');
        return [];
    }
});

export const options = {
    vus: 10,
    duration: '30s',
};

const BASE_URL = 'http://119.91.218.96:58080';

export default function () {
    if (users.length === 0) {
        console.error('No users found in users.json');
        sleep(1);
        return;
    }

    // Pick a random user
    const user = users[Math.floor(Math.random() * users.length)];
    
    const payload = JSON.stringify({
        title: `Article by ${user.userName} - ${new Date().getTime()}`,
        content: `This is a test article content generated by k6. Random content: ${Math.random()}`,
        boardId: 1 // Assuming board 1 exists
    });

    let token = user.token;
    if (token && !token.startsWith('Bearer ')) {
        token = `Bearer ${token}`;
    }

    const params = {
        headers: {
            'Content-Type': 'application/json',
            'Authorization': token
        },
    };

    const res = http.post(`${BASE_URL}/article/create`, payload, params);

    check(res, {
        'is status 200': (r) => r.status === 200,
        'is success code': (r) => r.json('code') === 200,
    });

    if (res.status !== 200) {
        console.error(`Failed to create article: ${res.status} ${res.body}`);
    }

    sleep(1);
}
